### ISSUE TITLE
SSL Server Test show A rating for census.gov but show not supported https

### ISSUE THREAD

**Issue by codexena** [18F/pulse#554] opened 2016-09-19 13:13 UTC
Not sure what other tests are being conducted, but the census.gov site supports both http and https and has been validated as a A rating by www.ssllabs.com.  It would be interesting how these sites are being testing and what is the criteria to show no support when the site can clearly support https.  Thou there are some sub-pages and applications that are being fixed that does not support https. The site has been able to support https for over a year now in general thus why I am asking the question.  The reference test URL that produced an A rating is: https://www.ssllabs.com/ssltest/analyze.html?viaform=on&d=www.census.gov

**Comment by alex** [comment] 2016-09-19 13:19
Hi @codexena, the problem appears to be that `census.gov` (no `www`), serves a certificate for the wrong domain: https://www.ssllabs.com/ssltest/analyze.html?d=census.gov

If the certificate for either `domain.gov` or `www.domain.gov` has a hostname-mismatch, pulse treats it as not having HTTPS.

Interestingly, I'm not able to reproduce this with my browser, but it shows up easily from a command line tool:

```
~ $ curl https://census.gov
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

and

```
~ $ /usr/local/opt/openssl/bin/openssl  s_client -connect census.gov:443 | openssl x509 -text -noout
depth=2 C = US, O = "VeriSign, Inc.", OU = VeriSign Trust Network, OU = "(c) 2006 VeriSign, Inc. - For authorized use only", CN = VeriSign Class 3 Public Primary Certification Authority - G5
verify return:1
depth=1 C = US, O = Symantec Corporation, OU = Symantec Trust Network, CN = Symantec Class 3 Secure Server CA - G4
verify return:1
depth=0 C = US, ST = District of Columbia, L = Washington, O = U.S. Census Bureau, OU = SSD, CN = www.census.gov
verify return:1
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            18:d5:ef:23:26:58:a1:e7:5b:0b:a3:4a:e8:7c:03:9a
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 Secure Server CA - G4
        Validity
            Not Before: May 16 00:00:00 2016 GMT
            Not After : May 30 23:59:59 2017 GMT
        Subject: C=US, ST=District of Columbia, L=Washington, O=U.S. Census Bureau, OU=SSD, CN=www.census.gov
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
            RSA Public Key: (2048 bit)
                Modulus (2048 bit):
                    00:a2:50:d8:d7:09:c9:4e:93:1e:59:68:86:bf:2d:
                    a9:80:b4:fe:81:e3:64:a0:1e:29:85:4f:64:06:7b:
                    ff:79:41:a2:d7:ce:3c:53:93:95:8b:f2:57:56:c0:
                    0c:31:7d:48:73:d1:e2:c9:d8:e5:e2:8b:76:96:66:
                    53:da:69:66:41:1d:04:99:da:a1:00:27:03:fc:24:
                    1f:2e:70:6f:98:f5:4d:83:e6:5f:32:73:97:0d:5c:
                    c6:e0:9d:d5:9e:db:0b:d2:a0:b0:52:09:6e:98:bf:
                    34:2d:0c:0a:49:b1:9c:7e:7c:06:4e:9d:a9:5b:61:
                    4e:cc:70:ff:b0:0e:2e:f0:a6:3e:b2:e6:3c:68:13:
                    e2:13:a1:9b:25:14:45:6f:6f:6a:91:72:a3:1a:18:
                    53:bb:97:dc:58:e8:22:ed:34:74:46:e8:39:1a:28:
                    d3:4b:40:ac:89:07:60:2b:b6:f3:8c:1c:03:b4:72:
                    53:d9:c6:31:83:88:77:42:b1:61:cf:c1:3c:03:00:
                    14:29:b5:38:90:1c:04:02:18:ab:49:ae:a4:7f:33:
                    99:4a:61:ee:59:b3:09:c4:9f:22:ce:3c:79:2e:bf:
                    76:6f:2b:b5:9e:89:d4:f6:fe:17:4e:4c:9b:cb:2b:
                    dd:1a:b2:53:f2:9f:9b:8e:97:21:44:2a:b7:2b:af:
                    e0:8d
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Alternative Name:
                DNS:www.census.gov
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Certificate Policies:
                Policy: 2.23.140.1.2.2
                  CPS: https://d.symcb.com/cps
                  User Notice:
                    Explicit Text: https://d.symcb.com/rpa

            X509v3 Authority Key Identifier:
                keyid:5F:60:CF:61:90:55:DF:84:43:14:8A:60:2A:B2:F5:7A:F4:43:18:EF

            X509v3 CRL Distribution Points:
                URI:http://ss.symcb.com/ss.crl

            Authority Information Access:
                OCSP - URI:http://ss.symcd.com
                CA Issuers - URI:http://ss.symcb.com/ss.crt

            1.3.6.1.4.1.11129.2.4.2:
O. ....hp~.....\..=..........T.V.z.....F0D. i?u..x..|.....$..j.e..*....zY.?[. ....sUg.'X..Y.......e.d...q..Yu..v.......X......gp
.....T.V.......G0E. AdU....^....T'XvL~..m. .....!. M.!..|.;.^.$....j.T.7..k.NT'...B.*q/
    Signature Algorithm: sha256WithRSAEncryption
        66:fd:e6:d5:f2:09:b2:ee:56:e5:92:16:95:cc:93:28:9d:15:
        a4:9e:c8:fc:52:32:c5:d0:76:ea:6e:db:35:6a:f5:a3:9b:aa:
        85:4b:31:fa:b3:fb:dd:d6:16:28:0e:6b:0d:72:43:4a:14:e9:
        a2:9e:73:d9:fc:24:97:ce:d7:36:57:6f:c4:ea:50:2f:b8:32:
        dc:8e:7c:74:53:b0:99:ba:7b:08:f5:cc:91:be:d4:bf:9d:93:
        90:78:58:89:aa:e8:4c:6c:6f:59:b2:e6:a2:68:d1:af:52:fb:
        84:49:ce:ba:2e:27:6d:83:a8:91:e0:c8:88:10:06:f3:61:96:
        86:6b:9c:d3:9d:39:d4:4a:dc:e1:4d:44:7f:47:8d:a1:5c:be:
        b5:be:c7:58:14:74:5f:75:36:6b:ce:c6:cf:20:ba:2e:15:cb:
        73:8f:ed:0d:e3:5e:07:63:c2:0d:09:03:27:d2:3a:63:81:17:
        9c:9a:45:1c:db:ff:b2:87:26:33:08:97:72:47:04:87:2a:10:
        eb:e2:b3:e3:f6:a0:a4:c9:a5:c0:b9:7b:9a:83:7a:80:58:c1:
        4c:b2:00:2a:1d:76:b9:b1:2e:5e:82:44:05:6b:f9:71:1e:64:
        1d:25:f3:63:49:2a:93:e1:ae:f4:af:1a:f4:e3:d0:d8:c1:cb:
        2e:37:86:a0
```

**Comment by gbinal** [comment] 2016-10-14 16:07
Given the responses above, I'm going to go ahead and close this. Feel free to open if there's an outstanding issue with Pulse.

**Closed by gbinal** 2016-10-14 16:07 UTC
