### ISSUE TITLE
Document a11y reporting methodology

### ISSUE THREAD

**Issue by adelevie** [18F/pulse#296] opened 2015-09-11 18:36 UTC
cc @jtexnl @nickbristow

**Comment by gbinal** [comment] 2015-09-11 18:39
This should encompass include the intended layout for pulse.cio.gov (i.e. what information will be displayed)

**Comment by nickbristow** [comment] 2015-09-11 18:50
Questions that need answering:
What statistics are shown per site?
How is the report shown?
  Show only the most recent?
  Show changes over time?
  Do we roll up the errors ala code sniffer?
Do we give the sites a health rating?
How do we show site accessibility progression?

**Comment by jtexnl** [comment] 2015-09-14 11:41
Since we're looking at using a sort of historical data approach to this, I would like to bring @konklone into the conversation here. He and I were discussing adding a DB, so I want to sync up these conversations.

**Comment by konklone** [comment] 2015-09-14 13:22
We've migrated the app to Flask, and opened up the possibility of using a database. Right now, it's just data files loaded into memory.

@nickbristow @adelevie What do you need in order to construct the display you want?

**Comment by adelevie** [comment] 2015-09-14 13:28
For persistence, a NoSQL db like Mongo should be plenty.

**Comment by konklone** [comment] 2015-09-14 13:51
@adelevie I meant more specifically - what's the shape of the data being stored? I'm trying to think about:

* Could ongoing disk storage (or S3 storage) with data loaded on app boot and held in memory be sufficient? (Probably not, but it is currently.)
* If a database is needed, is everyone cool with NoSQL? (I think we likely are.)
* If a NoSQL database is used, would Mongo be needed or would LevelDB (a local file, like SQLite) work well?
* How large is the data being stored, and would it make sense to give the 508 scanner its own collection/table? Or should we define a few common fields all scanners should save and have them all save data there? Also relevant: is historical data in the same collection as the current scan data via nesting, or is historical data connected via a reference/join to current data?

**Comment by normanbrobinson** [comment] 2016-04-18 20:24
If it is of any benefit from someone who did this internally at a large government agency, the actual errors are typically only used to benefit the site owners, and not kept for longer than the latest report. The reporting methods are basically for two different audiences; one for site owners or developers who might check the web content ad-hoc at any time and another audience using the comparative snapshots as an IT Governance function to show trending.

The actual reporting could roll up into a typical IT Dashboard Green, Yellow, Red approach, based on thresholds. That roll up reporting is then used as a baseline, with trending for each period (typically a quarter) to show improvements or regression. 

For the site page data or error reporting, it is typically by URL broken down into domain, then site. That data can vary from report to report, as sites or pages are created and removed with the same domain, and thus the baseline counts as well as shows percentages as delta between reporting periods.

**Comment by gbinal** [comment] 2016-08-17 17:23
This has been superseded by #406, so closing.

**Closed by gbinal** 2016-08-17 17:23 UTC
