### ISSUE TITLE
Incorrect https result for www.sba.gov

### ISSUE THREAD

**Issue by mapoling** [18F/pulse#247] opened 2015-07-06 17:57 UTC
I am a member of the Small Business Administration's Web team. We manage www.sba.gov and noticed that sba.gov is listed as not utilizing https but we do in fact use https for sba.gov. Thanks.

Marc Poling
Information Specialist
Small Business Administration

**Comment by konklone** [comment] 2015-07-07 22:08
Hi Marc -- So it looks like our scanner, which is based on `libcurl` (also used by the `curl` command line tool), is having some trouble connecting to sba.gov over HTTPS.

Coincidentally enough, I remembered running into this in a (personal, non-GSA) project recently that downloads inspector general reports from agency websites: https://github.com/unitedstates/inspectors-general/pull/217

The issue turned out to be an [buggy TLS implementation in an F5 load balancer](https://support.f5.com/kb/en-us/solutions/public/14000/700/sol14758.html) that required locking the connecting client to TLS 1.0. Attempts to negotiate the connection protocol dynamically failed. 

I can verify this using `curl`, on Ubuntu 14.10 (using `libssl`). When I try to connect with dynamic protocol negotiation, the connection hangs:

```
$ curl --head https://www.sba.gov

curl: (35) Unknown SSL protocol error in connection to www.sba.gov:443
```

When I force TLSv1.0, I can connect:

```
$ curl --head --tlsv1.0 https://www.sba.gov

HTTP/1.1 200 OK
Server: nginx
Date: Tue, 07 Jul 2015 21:56:51 GMT
Content-Type: text/html; charset=utf-8
...
```

To be clear, the issue is not that sba.gov only supports TLSv1.0. The issue is that some industry standard tools like cURL can't connect without special intervention to disable protocol negotiation. From our perspective, I'm not comfortable coding in an exception for sba.gov -- that's an upstream problem with sba.gov's load balancers that likely affects other users of sba.gov. So I'm comfortable with Pulse showing that sba.gov doesn't use HTTPS, since it currently doesn't correctly support HTTPS for some standard HTTP clients.

It's worth fixing this not just to let our scanners connect successfully, but also to [improve sba.gov's overall TLS quality](https://www.ssllabs.com/ssltest/analyze.html?d=sba.gov&latest). TLS 1.0 support is still required in practice for some older clients, but TLS 1.0 is not considered wonderfully secure today. It's a very minor change from its predecessor SSLv3, which is now [formally deprecated as insecure](https://tools.ietf.org/html/rfc7568), and [NIST Special Publication 800-52](http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-52r1.pdf) already disallows TLSv1.0 for government-facing systems in favor of TLS 1.2.

I suggest resolving the issue by fixing or replacing your load balancers to support TLS 1.2, which should also resolve the connection issues we're observing with `libcurl`.

**Comment by oscar-ahumada** [comment] 2015-07-28 16:24
We are getting similar results for the FDIC, where the majority of our websites are on HTTPS but Pulse is reporting 22% for our agency.  I suspect many other federal sites may be getting similar results due to load balancers or configuration issues.  For the next scan, I'd recommend adding the code above and creating a 3rd category for "HTTPS detected with issues".  This would be both more accurate and more helpful for the agency admins who need to implement the changes.
Thanks.

**Comment by konklone** [comment] 2015-07-29 05:31
> We are getting similar results for the FDIC, where the majority of our websites are on HTTPS but Pulse is reporting 22% for our agency.

@oscar-ahumada This isn't what I see for the FDIC on Pulse. Pulse currently says the FDIC uses HTTPS for 29% of its second-level domains, which is [2 out of 7 domains](https://pulse.cio.gov/https/domains/#q=Federal%20Deposit%20Insurance%20Corporation). 

Of the other 5 domains:

* `fdicbets.gov`
* `fdicconnect.gov`
* `fdicseguro.gov`
* `myfdic.gov`
* `myfdicinsurance.gov`

I can't reach any of these over HTTPS in my browser, either. A couple of them redirect to `https://www.fdic.gov`, but the redirect domain doesn't itself support HTTPS. `fdic.gov` is correctly shown on Pulse as supporting HTTPS.

So I don't have any evidence that the F5 load balancer issue I described above is currently affecting FDIC's numbers on Pulse.

**Comment by konklone** [comment] 2015-08-28 18:25
Closing, as I don't believe the issue is a Pulse methodology problem. Happy to discuss further.

**Closed by konklone** 2015-08-28 18:25 UTC
